name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      # --- PASSO NOVO E CRUCIAL ---
      - name: Create output directory
        run: mkdir -p dist

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          # Agora dizemos explicitamente para salvar na pasta que acabamos de criar
          outputs: dist/snake.svg
          color_snake: "#fe8019"
          color_dots: "#458588,#689d6a,#98971a,#b8bb26,#fabd2f"

      - name: Push to output branch
        # Este passo agora vai funcionar, pois a pasta 'dist' vai existir
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
