name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        # --- AQUI ESTÁ A CORREÇÃO FINAL DA VERSÃO ---
        uses: sowdane/snake-game-action@v4
        with:
          github_user_name: ${{ github.repository_owner }}
          
          output: dist/snake.svg
          
          color_snake: "#fe8019"
          color_dots: "#458588,#689d6a,#98971a,#b8bb26,#fabd2f"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
