name: Generate Snake Animation

on:
  schedule:
    # Roda a cada 12 horas
    - cron: "0 */12 * * *"
  
  # Permite que você rode manualmente pela aba Actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Permissão para a action escrever no repositório
      
    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk/svg-only@v3
        with:
          # Seu nome de usuário do GitHub
          github_user_name: ${{ github.repository_owner }}
          
          # Arquivos de saída, salvos na raiz do branch 'output'
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          # O branch onde o SVG será salvo
          target_branch: output
          # O diretório que contém o SVG a ser publicado
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}