name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake SVG
        # --- AQUI ESTÁ A MUDANÇA PRINCIPAL ---
        uses: andry81/gh-action-snake@v1.0.3
        with:
          # O nome do arquivo de saída (a nova action usa OUT_PATH)
          OUT_PATH: "dist/snake.svg"
          # A cor da cobra (a nova action usa COLOR_SNAKE)
          COLOR_SNAKE: "#fe8019"
          # As cores dos pontos (a nova action usa COLOR_DOTS)
          COLOR_DOTS: "#458588,#689d6a,#98971a,#b8bb26,#fabd2f"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}